# Generated by Django 2.2.6 on 2019-11-03 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoutineName', models.CharField(max_length=30)),
                ('WorkoutLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gymobile_app.WorkoutLog')),
            ],
        ),
        migrations.CreateModel(
            name='Exercies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('bodypart', models.CharField(choices=[('Back Exercies', 'Back'), ('Legs Exercies', 'Leg'), ('Shoulder Exercies', 'Shoulder'), ('Chest Exercies', 'Chest')], default='Back Exercies', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=500)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gymobile_app.WorkoutLog')),
            ],
            options={
                'verbose_name_plural': 'exercies',
            },
        ),
    ]
