# Generated by Django 2.2.1 on 2019-06-30 20:21

import Gymobile_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=Gymobile_app.models.Day.number, unique=True, verbose_name='Workout day')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('Back Day', 'Back'), ('Legs Day', 'Leg'), ('Shoulder Day', 'Shoulder'), ('Chest Day', 'Chest')], default='Back Day', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gymobile_app.Day')),
            ],
            options={
                'verbose_name_plural': 'workouts',
            },
        ),
    ]
