# Generated by Django 2.2.6 on 2019-11-05 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='user',
            new_name='owner',
        ),
    ]
