# Generated by Django 2.1.5 on 2019-05-12 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0002_auto_20190512_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='data_added',
        ),
        migrations.RemoveField(
            model_name='day',
            name='text',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 17, 24, 52, 71154)),
        ),
    ]
