# Generated by Django 2.1.5 on 2019-07-03 01:20

import Gymobile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0002_day_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.IntegerField(default=Gymobile_app.models.Day.number, verbose_name='Workout day'),
        ),
    ]
