# Generated by Django 2.2.1 on 2019-07-07 13:47

import Gymobile_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0003_auto_20190703_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.IntegerField(default=Gymobile_app.models.Day.number, unique=True, verbose_name='Workout day'),
        ),
    ]
