# Generated by Django 2.2.1 on 2019-07-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0004_auto_20190707_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.IntegerField(default='', unique=True, verbose_name='Workout day'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise',
            field=models.CharField(choices=[('Back Exercies', 'Back'), ('Legs Exercies', 'Leg'), ('Shoulder Exercies', 'Shoulder'), ('Chest Exercies', 'Chest')], default='Back Exercies', max_length=15),
        ),
    ]
