# Generated by Django 2.1.5 on 2019-05-12 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0005_auto_20190512_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='data_added',
        ),
        migrations.AddField(
            model_name='day',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 11, 17, 29, 13, 209390)),
        ),
    ]
