# Generated by Django 2.1.5 on 2019-05-12 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0006_auto_20190512_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 32, 18, 30672)),
        ),
    ]
