# Generated by Django 2.1.5 on 2019-05-12 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0007_auto_20190512_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 33, 20, 36421)),
        ),
    ]
