# Generated by Django 2.1.5 on 2019-05-12 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0009_auto_20190512_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'workouts',
            },
        ),
        migrations.RemoveField(
            model_name='day',
            name='day_added',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 40, 59, 590612)),
        ),
        migrations.AddField(
            model_name='workout',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gymobile_app.Day'),
        ),
    ]
