# Generated by Django 2.1.5 on 2019-05-12 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gymobile_app', '0011_auto_20190512_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 43, 1, 299008)),
        ),
    ]
