# Generated by Django 2.2.1 on 2019-07-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190708_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='FirstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='LastName',
            new_name='last_name',
        ),
    ]
