# Generated by Django 2.2.1 on 2019-07-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190708_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
